# Generated by Django 3.1.7 on 2021-06-17 09:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tg_response_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, verbose_name='Команда')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст ответа')),
            ],
        ),
    ]
