# Generated by Django 3.1.7 on 2021-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_tg_response_msg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tg_response_msg',
            options={'verbose_name': 'Ответ на команду', 'verbose_name_plural': 'Ответы на команды'},
        ),
        migrations.AlterField(
            model_name='tg_response_msg',
            name='command',
            field=models.CharField(max_length=255, unique=True, verbose_name='Команда'),
        ),
    ]
