# Generated by Django 3.1.7 on 2021-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_auto_20210617_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_response_msg',
            name='content',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
    ]
