# Generated by Django 3.1.7 on 2021-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_auto_20210628_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_admin',
            field=models.BooleanField(default=False),
        ),
    ]
