# Generated by Django 3.1.6 on 2021-03-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proauto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('previewImg', models.ImageField(upload_to='photo_auto/brend', verbose_name='Логотип')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proauto.menu', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('previewImg', models.ImageField(upload_to='photo_auto/preview', verbose_name='Картинка предпросмотра')),
                ('mainImg', models.ImageField(upload_to='photo_auto/mainimg', verbose_name='Основная картинка')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proauto.brend', verbose_name='Категория')),
            ],
        ),
    ]
