# Generated by Django 3.1.6 on 2021-03-10 11:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proauto', '0002_auto_brend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='brend',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proauto.menu', verbose_name='Принадлежность к стране'),
        ),
    ]
