# Generated by Django 3.1.6 on 2021-03-10 12:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proauto', '0003_auto_20210310_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы')),
                ('flagImg', models.ImageField(upload_to='photo_auto/flag', verbose_name='Флаг страны')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proauto.menu', verbose_name='Категория')),
            ],
        ),
    ]
