# Generated by Django 3.1.6 on 2021-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proauto', '0005_auto_20210318_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('massage', models.TextField(max_length=1500, verbose_name='Текст обращения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['production_date', 'title'], 'verbose_name': 'Модели автомобилей', 'verbose_name_plural': 'Модели автомобилей'},
        ),
    ]
