# Generated by Django 3.1.6 on 2021-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proauto', '0007_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True,  verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
